=== edesmontils/WA/page_mediawiki.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT page (revision+)> <!-- ((revision|upload)*)  -->
<!ATTLIST page 
    title CDATA #REQUIRED
    id ID #IMPLIED>
  
<!ELEMENT revision (contributor,comment?,text?, change-list?)>
<!ATTLIST revision
    id ID #IMPLIED
    timestamp CDATA #REQUIRED>

<!ELEMENT comment (#PCDATA)> 

<!ELEMENT text (#PCDATA)>          <!-- Wikisyntax -->
<!ATTLIST text xml:space CDATA  #FIXED "preserve">
    
<!ELEMENT contributor EMPTY>
<!ATTLIST contributor
    id CDATA #IMPLIED
    name CDATA #IMPLIED
    ip CDATA #IMPLIED>
    
<!ELEMENT change-list (insert | delete | change)* >
<!ELEMENT insert EMPTY >
<!ATTLIST insert line CDATA #REQUIRED txt CDATA #REQUIRED >

<!ELEMENT delete EMPTY >
<!ATTLIST delete line CDATA #REQUIRED txt CDATA #IMPLIED >

<!ELEMENT change (insert | delete)* >

<!--ELEMENT upload (contributor,comment?)>
<!ATTLIST upload
    timestamp CDATA #REQUIRED
    filename CDATA #REQUIRED
    src CDATA #REQUIRED
    size CDATA #REQUIRED-->

=== edesmontils/WA/files/Math/Math_ns_Algèbre_und_générale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE page
SYSTEM "http://www.desmontils.net/ns/page_mediawiki.dtd">
<page title="Math:Algèbre générale" id="p9">
 <revision id="r15" timestamp="2002-02-20T20:11:08Z">
  <contributor name="Youssefsan"/>
  <comment>+liens non encore classés : produits remarquable</comment>
  <change-list>
   <insert line="1" txt="'''Bases'''"/>
   <insert line="2" txt=""/>
   <insert line="3" txt=":[[Ensemble]]"/>
   <insert line="4" txt=""/>
   <insert line="5" txt=":[[Application]]"/>
   <insert line="6" txt=""/>
   <insert line="7" txt=":[[Lois ou opération]]"/>
   <insert line="8" txt=""/>
   <insert line="9" txt=""/>
   <insert line="10" txt=""/>
   <insert line="11" txt="'''Structures algèbriques'''"/>
   <insert line="12" txt=""/>
   <insert line="13" txt=":[[Groupe]]"/>
   <insert line="14" txt=""/>
   <insert line="15" txt=":[[Morphismes]]"/>
   <insert line="16" txt=""/>
   <insert line="17" txt=":[[Anneaux et corps]]"/>
   <insert line="18" txt=""/>
   <insert line="19" txt=""/>
   <insert line="20" txt=""/>
   <insert line="21" txt=""/>
   <insert line="22" txt=""/>
   <insert line="23" txt="----"/>
   <insert line="24" txt=""/>
   <insert line="25" txt=""/>
   <insert line="26" txt=""/>
   <insert line="27" txt="Liens non encore classés :"/>
   <insert line="28" txt=""/>
   <insert line="29" txt=""/>
   <insert line="30" txt=""/>
   <insert line="31" txt="[[Produits remarquables]]"/>
   <insert line="32" txt=""/>
   <insert line="33" txt=""/>
  </change-list>
 </revision>
 <revision id="r16" timestamp="2002-08-15T13:43:30Z">
  <contributor name="Sept"/>
  <comment>Ajout lien discuter</comment>
  <change-list>
   <insert line="4" txt=""/>
   <insert line="5" txt=":[[Sous-ensemble]]"/>
   <insert line="6" txt=""/>
   <insert line="7" txt=":[[Opération ensembliste]]"/>
   <insert line="8" txt=""/>
   <insert line="9" txt=":[[Relation]]"/>
   <insert line="12" txt=""/>
   <insert line="13" txt=":[[Produit cartésien]]"/>
   <insert line="40" txt=""/>
   <insert line="41" txt=""/>
   <insert line="42" txt=""/>
   <insert line="43" txt="----"/>
   <insert line="44" txt=""/>
   <insert line="45" txt=""/>
   <insert line="46" txt=""/>
   <insert line="47" txt="[[/discuter]]"/>
  </change-list>
 </revision>
 <revision id="r17" timestamp="2002-08-20T13:39:11Z">
  <contributor name="Sept"/>
  <comment>*</comment>
  <change-list>
   <delete line="2" txt=""/>
   <delete line="3" txt=""/>
   <delete line="4" txt=""/>
   <delete line="5" txt=""/>
   <delete line="6" txt=""/>
   <delete line="7" txt=""/>
   <delete line="8" txt=""/>
   <delete line="9" txt=""/>
   <delete line="9" txt=""/>
   <delete line="11" txt=""/>
   <delete line="12" txt=""/>
   <delete line="13" txt=""/>
   <change>
    <delete line="15" txt=""/>
    <delete line="15" txt=""/>
    <delete line="15" txt=""/>
    <delete line="15" txt=""/>
    <insert line="15" txt="'''Théorie des sous-ensembles flous'''"/>
    <insert line="16" txt=":[[Sous-ensemble flou]]"/>
    <insert line="17" txt=":[[Opérateur flou]]"/>
   </change>
   <delete line="19" txt=""/>
   <delete line="19" txt=""/>
   <delete line="21" txt=""/>
   <delete line="21" txt=""/>
   <delete line="23" txt=""/>
   <delete line="23" txt=""/>
   <delete line="25" txt=""/>
   <delete line="25" txt=""/>
   <delete line="27" txt=""/>
  </change-list>
 </revision>
 <revision id="r11091" timestamp="2002-10-31T10:11:31Z">
  <contributor name="script de conversion"/>
  <comment>Conversion automatique</comment>
  <change-list>
   <delete line="25" txt=""/>
   <delete line="25" txt="[[/discuter]]"/>
  </change-list>
 </revision>
 <revision id="r24024" timestamp="2002-11-08T13:04:15Z">
  <contributor ip="203.218.206.104"/>
  <change-list>
   <insert line="1" txt="[[en:Abstract algebra]]"/>
   <delete line="26" txt=""/>
  </change-list>
 </revision>
 <revision id="r24179" timestamp="2003-01-23T14:59:28Z">
  <contributor name="Snark" id="u182"/>
  <change-list>
   <change>
    <delete line="9" txt=":[[Lois ou opération]]"/>
    <insert line="9" txt=":[[Loi de composition interne]]"/>
   </change>
  </change-list>
 </revision>
 <revision id="r24191" timestamp="2003-01-24T08:40:48Z">
  <contributor name="Snark" id="u182"/>
  <comment>ajout des magmas et monoïdes</comment>
  <change-list>
   <change>
    <delete line="5" txt=":[[Opération ensembliste]]"/>
    <insert line="5" txt=":[[Opérations ensemblistes]]"/>
   </change>
   <insert line="12" txt=":[[Monoïdes et magmas]]"/>
  </change-list>
 </revision>
 <revision id="r24264" timestamp="2003-01-24T09:10:15Z">
  <contributor name="Snark" id="u182"/>
  <comment>le produit cartésien est une opération ensembliste</comment>
  <change-list>
   <delete line="8" txt=":[[Produit cartésien]]"/>
  </change-list>
 </revision>
 <revision id="r24269" timestamp="2003-01-24T14:32:59Z">
  <contributor name="Snark" id="u182"/>
  <comment>séparation d'anneaux et corps</comment>
  <change-list>
   <change>
    <delete line="14" txt=":[[Anneaux et corps]]"/>
    <insert line="14" txt=":[[anneau|Anneaux]]"/>
    <insert line="15" txt=":[[corps|Corps]]"/>
   </change>
  </change-list>
 </revision>
 <revision id="r24456" timestamp="2003-01-24T14:52:19Z">
  <contributor name="Snark" id="u182"/>
  <comment>ajout de construction des objets courants</comment>
  <change-list>
   <insert line="9" txt=":[[Construction des objets courants]]"/>
  </change-list>
 </revision>
 <revision id="r24467" timestamp="2003-01-25T09:09:49Z">
  <contributor name="Snark" id="u182"/>
  <comment>Application =&gt; Fonction_et_Application</comment>
  <change-list>
   <change>
    <delete line="7" txt=":[[Application]]"/>
    <insert line="7" txt=":[[Fonction et application|Fonctions et applications]]"/>
   </change>
  </change-list>
 </revision>
 <revision id="r25361" timestamp="2003-01-25T09:31:46Z">
  <contributor name="Tarquin" id="u13"/>
  <comment>une intro pas terrible</comment>
  <change-list>
   <insert line="2" txt=""/>
   <insert line="3" txt="L''''algèbre abstraite''' est une branche des [[mathématiques]] qui se concerne principalement des structures et des fonctions entre elles."/>
   <insert line="4" txt=""/>
  </change-list>
 </revision>
 <revision id="r25499" timestamp="2003-01-29T17:24:59Z">
  <contributor name="Snark" id="u182"/>
  <comment>lien &quot;groupe&quot; -&gt; &quot;groupe (mathématiques)</comment>
  <change-list>
   <change>
    <delete line="16" txt=":[[Groupe]]"/>
    <insert line="16" txt=":[[groupe (mathématiques)|Groupe]]"/>
   </change>
  </change-list>
 </revision>
 <revision id="r33377" timestamp="2003-01-30T13:07:44Z">
  <contributor name="Snark" id="u182"/>
  <comment>la construction des objets courants devrait être plus visible...</comment>
  <change-list>
   <delete line="12" txt=":[[Construction des objets courants]]"/>
  </change-list>
 </revision>
 <revision id="r33563" timestamp="2003-03-05T16:12:59Z">
  <contributor name="Med" id="u137"/>
  <comment>,</comment>
  <change-list>
   <change>
    <delete line="3" txt="L''''algèbre abstraite''' est une branche des [[mathématiques]] qui se concerne principalement des structures et des fonctions entre elles."/>
    <insert line="3" txt="L''''algèbre abstraite''' est une branche des [[mathématiques]], qui concerne principalement des structures et des fonctions entre elles."/>
   </change>
  </change-list>
 </revision>
 <revision id="r110030" timestamp="2003-03-06T07:15:19Z">
  <contributor name="Snark" id="u182"/>
  <comment>francisation de la phrase</comment>
  <change-list>
   <change>
    <delete line="3" txt="L''''algèbre abstraite''' est une branche des [[mathématiques]], qui concerne principalement des structures et des fonctions entre elles."/>
    <insert line="3" txt="L''''algèbre abstraite''' est une branche des [[mathématiques]], qui porte principalement sur l'étude des structures et des fonctions entre elles."/>
   </change>
   <insert line="28" txt=""/>
  </change-list>
 </revision>
 <revision id="r134707" timestamp="2003-09-03T22:50:54Z">
  <contributor name="Looxix" id="u328"/>
  <comment>corps (mathématiques)|</comment>
  <change-list>
   <change>
    <delete line="18" txt=":[[corps|Corps]]"/>
    <insert line="18" txt=":[[corps (mathématiques)|corps]]"/>
   </change>
  </change-list>
 </revision>
 <revision id="r202156" timestamp="2003-10-17T11:58:03Z">
  <contributor name="Guéna" id="u1120"/>
  <comment>Il manquait une majuscule à corps.</comment>
  <change-list>
   <change>
    <delete line="18" txt=":[[corps (mathématiques)|corps]]"/>
    <insert line="18" txt=":[[corps (mathématiques)|Corps]]"/>
   </change>
  </change-list>
 </revision>
 <revision id="r235120" timestamp="2003-12-15T13:37:52Z">
  <contributor name="Mikue" id="u307"/>
  <comment>+de:</comment>
  <change-list>
   <insert line="1" txt="[[de:Abstrakte Algebra]]"/>
  </change-list>
 </revision>
 <revision id="r245787" timestamp="2004-01-20T19:51:38Z">
  <contributor name="HasharBot" id="u1269"/>
  <comment>HasharBot - robot  Ajoute:ru</comment>
  <change-list>
   <change>
    <delete line="1" txt="[[de:Abstrakte Algebra]]"/>
    <delete line="1" txt="[[en:Abstract algebra]]"/>
    <insert line="1" txt="[[de:Abstrakte Algebra]] [[en:Abstract algebra]] [[ru:Абстрактная алгебра]]"/>
   </change>
  </change-list>
 </revision>
 <revision id="r316958" timestamp="2004-02-01T14:01:25Z">
  <contributor ip="217.227.67.216"/>
  <change-list>
   <change>
    <delete line="1" txt="[[de:Abstrakte Algebra]] [[en:Abstract algebra]] [[ru:Абстрактная алгебра]]"/>
    <insert line="1" txt="[[de:Abstrakte Algebra]]"/>
    <insert line="2" txt="[[en:Abstract algebra]]"/>
    <insert line="3" txt="[[he:אלגברה מופשטת]]"/>
    <insert line="4" txt="[[ru:Абстрактная алгебра]]"/>
   </change>
  </change-list>
 </revision>
 <revision id="r340852" timestamp="2004-03-17T12:02:04Z">
  <contributor name="Guillaumito" id="u2833"/>
  <comment>lien monoide/magma</comment>
  <change-list>
   <change>
